In [20]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_excel('.\附件2\Ins1_5_10_3.xlsx', sheet_name=2)
df

Unnamed: 0  墨盒1  墨盒2  墨盒3  墨盒4  墨盒5  墨盒6  墨盒7  墨盒8  墨盒9  墨盒10
0        墨盒1    0   10    3   15    9   10   10    3    7     8
1        墨盒2   12    0   10   16    4   17   16   15   19     9
2        墨盒3   12    9    0   15   10    7    8   15    9     9
3        墨盒4   12    9    8    0   11   15    8   12   12    14
4        墨盒5    8    7   11   23    0   18   18   11   15    16
5        墨盒6    5    2    8    9    4    0    1    8    5     2
6        墨盒7    4    1    7   14    3   14    0    7    4     7
7        墨盒8   10    7   13   14    6   18   18    0    4     7
8        墨盒9   10    9   13   10    2   14   14    9    0     3
9       墨盒10   17   14   15    7   13   12   13   17   14     0

In [31]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [32]:
array = df.values
array = np.array(array)
count = 0
for i in range(array.shape[0]):           # 确定条件保证 墨盒i->墨盒j->墨盒k > 墨盒i->墨盒k
    for j in range(array.shape[1]):
        for k in range(array.shape[0]):
            if array[i][j] > array[i][k] + array[k][j]:
                count += 1
print(count)

0


In [33]:
array.shape[0]

10

In [35]:
a = np.array([0, 1])
a

array([0, 1])

In [36]:
list = [1, 2, 3]
list[a[0]]

1

In [40]:
list = np.array(range(27)).reshape(3, 3, 3)

In [41]:
list

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [42]:
list[0, 0, 0]

0

In [43]:
list

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [44]:
list[[0, 1], :]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [45]:
list[[0,1]]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [46]:
list = [1, 2, 3]
a = list.pop()

In [47]:
a

3

In [4]:
import random
import numpy as np

In [113]:
a = np.random.randint(5)
a

3

In [2]:
a

2

In [116]:
list = np.array([1, 2, 3, 4])
list[[1, 2]] = list[[2, 1]]

In [118]:
list = np.array([[1, 2, 3], [2, 3, 4]])

In [119]:
list

array([[1, 2, 3],
       [2, 3, 4]])

In [120]:
a = [4, 5, 6]

In [121]:
list[0] = a

In [122]:
list

array([[4, 5, 6],
       [2, 3, 4]])

In [1]:
for i in range(1):
    print(i)

0


In [29]:
list = np.array(range(27)).reshape(3, 3, 3)
np.random.shuffle(list[0])
list

array([[[ 3,  4,  5],
        [ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [30]:
list[0,[0, 1]] = list[0, [1, 0]]

In [31]:
list

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [2]:
x = [1, 2, 3]
a = x.pop()
a

3

In [3]:
x

[1, 2]