In [2]:
import pandas as pd
import numpy as np

In [3]:
a = np.array([1] * 100)

In [4]:
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
a = np.insert(a, 0, 1)

In [6]:
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
print(a)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [8]:
chrom = np.array([np.array([0] * 43) for _ in range(500)])
print(chrom.shape)

(500, 43)


In [9]:
for index, value in np.ndenumerate(chrom):
    print(index[1])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
1

In [10]:
import random
a = np.array(range(5, 10))
p1, p2 = random.choices(a[:], k=2)
p1, p2

(5, 8)

In [11]:
a = np.array(range(5, 10))
for index, value in np.ndenumerate(a):
    print(index)
    if index == len(a)-1:
        break
    if index == 0:
        a = np.insert(a, 0, 1000)
    if index == 3:
        a = np.insert(a, index, 1000)
print(a)

(0,)
(1,)
(2,)
(3,)
(4,)
[5 6 7 8 9]


In [12]:
a

array([5, 6, 7, 8, 9])

In [13]:
list(i for i in range(5, 10) if i != 7)

[5, 6, 8, 9]

In [14]:
a

array([5, 6, 7, 8, 9])

In [15]:
var_size_array = np.array([np.array([1, 2, 3]), np.array([4, 5]), np.array([6])])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
chrom[1]

In [ ]:
alist = [np.arange(i) for i in range(3,7)]

In [ ]:
alist

In [ ]:
for index, array in enumerate(alist):
    print(index)
    print(array)

In [ ]:
a = np.array([1, 2, 4, 5, 0, 4, 0, 2, 4])
decode_a = a[a > 0]
decode_a

In [ ]:
a = []

In [ ]:
a.append([x for x in range(18)])

In [ ]:
a = [1, 2, 3]
b = [2, 3, 4]
c = []

In [ ]:
a + b + c

In [ ]:
a = []
b = list(np.array([1, 2, 3]))

In [ ]:
a += b

In [ ]:
a

In [ ]:
a = [1, 2, 0, 1, 2]
b = np.where(np.array(a)== 0)[0]

In [ ]:
b

In [ ]:
index = np.argsort(a)[::-1]

In [ ]:
index

In [ ]:
a[[1:3 ]]=[3,4]

In [ ]:
a = [1, 2, 3, 0]
a[a == 0]

In [ ]:
df = pd.read_excel('./time_matrix.xlsx')

In [ ]:
df

In [ ]:
time_matrix = pd.read_excel('./time_matrix.xlsx')
time_matrix.set_index(['到达门店简称'], inplace=True)
time_matrix = time_matrix.to_numpy(dtype=float)

In [ ]:
time_matrix
a = time_matrix

In [ ]:
a[0, 2] + a[2, 14]+a[14, 38]

In [ ]:
a[0, 21] + a[21, 22] + a[22, 32] + a[32, 34] + a[34, 18] + a[18, 17]

In [ ]:
a[0, 42] + a[42, 20] + a[20, 5] + a[5, 31] + a[31, 13] + a[13, 19]

In [ ]:
a[0, 4] + a[4, 3] + a[3, 6] + a[6, 40] + a[40, 15]

In [ ]:
a[0, 8] + a[8, 29] + a[29, 35] + a[35, 9] + a[9, 7] + a[7, 36] + a[36, 41]

In [ ]:
a[23, 25] + a[25, 27] + a[27, 30] + a[30, 39]

In [ ]:
a[33, 37] + a[37, 10] + a[10, 11] + a[11, 1]

In [ ]:
a[0, 26] + a[26, 24] + a[24, 16] + a[16, 28] + a[28,43]

In [ ]:
df = pd.read_excel('./数据.xlsx', sheet_name=0)
df.drop(columns=['配送中心', '允许到店时间段'], inplace=True)
df['时间属性'] = df['时间属性'].map({'夜配': 0, '日配': 1})
df2 = pd.DataFrame(['配送中心', '120.44739', '31.50353', 2]).T
df2.columns = df.columns
df = pd.concat([df2, df], ignore_index=True)
df.drop(index=[3, 7, 23], inplace=True)
df.reset_index(inplace=True)
print(df)

In [ ]:
send_array = df['时间属性']
send_array = send_array.to_numpy(dtype=int)
print(send_array)

In [ ]:
send_array[2]

In [ ]:
send_array[14]

In [ ]:
send_array[38]

In [ ]:
send_array[21]

In [ ]:
send_array[22]

In [ ]:
send_array[32]

In [ ]:
send_array[34]

In [ ]:
send_array[18]

In [ ]:
send_array[17]

In [ ]:
send_array[42]

In [ ]:
send_array[20]

In [ ]:
send_array[5]

In [ ]:
send_array[31]

In [ ]:
send_array[4]

In [ ]:
send_array[3]

In [ ]:
send_array[6]

In [ ]:
send_array[40]

In [ ]:
send_array[8]

In [ ]:
send_array[29]

In [ ]:
send_array[12]

In [ ]:
send_array[23]

In [ ]:
send_array[25]

In [ ]:
send_array[33]

In [ ]:
send_array[37]

In [ ]:
send_array[10]

In [ ]:
send_array[11]

In [ ]:
send_array[1]

In [ ]:
send_array[26]

In [ ]:
df = pd.read_excel('./time_send.xlsx')

In [ ]:
df

In [ ]:
a = df.groupby(['日期'])

In [ ]:
b = list((a.get_group((4, ))['配送时间']).to_numpy())

In [ ]:
b

In [ ]:
b[0]

In [ ]:
df = pd.read_excel('./数据.xlsx', sheet_name=0)
df.drop(columns=['配送中心', '允许到店时间段'], inplace=True)
df['时间属性'] = df['时间属性'].map({'夜配': 0, '日配': 1})
df2 = pd.DataFrame(['配送中心', '120.44739', '31.50353', 2]).T
df2.columns = df.columns
df = pd.concat([df2, df], ignore_index=True)
df.drop(index=[3, 7, 23], inplace=True)
df.reset_index(inplace=True)

In [ ]:
send_data = pd.read_excel('./time_send.xlsx')
for i in send_data.index:
    filt = (df['到达门店简称'] == send_data.loc[i, '门店名称'])
    send_data.loc[i, '门店名称'] = df.loc[filt, '到达门店简称'].index[0]
send_data.index += 1

In [ ]:
send_data

In [ ]:
time_matrix = pd.read_excel('./time_matrix.xlsx')
time_matrix.set_index(['到达门店简称'], inplace=True)
time_matrix = time_matrix.to_numpy(dtype=float)

df = pd.read_excel('./数据.xlsx', sheet_name=0)
df.drop(columns=['配送中心', '允许到店时间段'], inplace=True)
df['时间属性'] = df['时间属性'].map({'夜配': 0, '日配': 1})
df2 = pd.DataFrame(['配送中心', '120.44739', '31.50353', 2]).T
df2.columns = df.columns
df = pd.concat([df2, df], ignore_index=True)
df.drop(index=[3, 7, 23], inplace=True)
df.reset_index(inplace=True)

send_data = pd.read_excel('./time_send.xlsx')
for i in send_data.index:
    filt = (df['到达门店简称'] == send_data.loc[i, '门店名称'])
    send_data.loc[i, '门店名称'] = df.loc[filt, '到达门店简称'].index[0]
df3 = pd.DataFrame([0, 0, 0, 0, 0]).T
df3.columns = send_data.columns
send_data = pd.concat([df3, send_data], ignore_index=True)
send_data['总货量'] = send_data['冷冻发货量(吨)'] + send_data['冷藏发货量(吨)']

In [ ]:
send_data

In [ ]:
distance_matrix = pd.read_excel('./distance_matrix.xlsx')
distance_matrix.set_index(['到达门店简称'], inplace=True)
distance_matrix = distance_matrix.to_numpy(dtype=float)
distance_matrix

In [ ]:
a = np.array([1, 2, 3])
a[0]

In [ ]:
df = pd.read_excel('./数据.xlsx', sheet_name=0)
df.drop(columns=['配送中心', '允许到店时间段'], inplace=True)
df['时间属性'] = df['时间属性'].map({'夜配': 0, '日配': 1})
df2 = pd.DataFrame(['配送中心', '120.44739', '31.50353', 2]).T
df2.columns = df.columns
df = pd.concat([df2, df], ignore_index=True)
df.drop(index=[3, 7, 23], inplace=True)
df.reset_index(inplace=True)
print(df)

time_matrix = pd.read_excel('./time_matrix.xlsx')
time_matrix.set_index(['到达门店简称'], inplace=True)
time_matrix = time_matrix.to_numpy(dtype=float)
print(time_matrix)
send_array = df['时间属性']
send_array = send_array.to_numpy(dtype=int)
print(send_array)

In [ ]:
set[1, 2] in set[1, 2, 3]

In [ ]:
a = [1, 2,4,4]

In [ ]:
a.count(4)

In [ ]:
time_matrix

In [ ]:
time_matrix[0, 30]+time_matrix[30, 29] + time_matrix[29,39] + time_matrix[39,33] + time_matrix[33, 13] + time_matrix[13, 19] + time_matrix[19, 31]  

In [ ]:
time_matrix[0, 5]+time_matrix[5, 37] + time_matrix[11,14] + time_matrix[37, 11]

In [ ]:
distance_matrix = pd.read_excel('./distance_matrix.xlsx')
distance_matrix.set_index(['到达门店简称'], inplace=True)
distance_matrix = distance_matrix.to_numpy()

In [ ]:
distance_matrix

In [ ]:
distance_matrix[1, 2]

In [22]:
a = [1, 2 , 3, 4 ,5]

In [23]:
b = [1, 2, 3 ,4,7, 8]

In [24]:
c = a + b

In [25]:
c

[1, 2, 3, 4, 5, 1, 2, 3, 4, 7, 8]

In [26]:
c = a
c

[1, 2, 3, 4, 5]

In [17]:
a = [1, 2, 3]
b = [2, 3 ,4]
a + b

[1, 2, 3, 2, 3, 4]

In [18]:
c = a + b

In [19]:
c

[1, 2, 3, 2, 3, 4]

In [20]:
c = a

In [21]:
c

[1, 2, 3]

In [27]:
c += list(a)

In [28]:
c

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [29]:
a += list(c)

In [30]:
a

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]