In [86]:
import pandas as pd
import numpy as np

In [87]:
a = np.array([1] * 100)

In [88]:
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [89]:
a = np.insert(a, 0, 1)

In [90]:
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [91]:
print(a)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [92]:
chrom = np.array([np.array([0] * 43) for _ in range(500)])
print(chrom.shape)

(500, 43)


In [93]:
for index, value in np.ndenumerate(chrom):
    print(index[1])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
1

In [94]:
import random
a = np.array(range(5, 10))
p1, p2 = random.choices(a[:], k=2)
p1, p2

(6, 6)

In [95]:
a = np.array(range(5, 10))
for index, value in np.ndenumerate(a):
    print(index)
    if index == len(a)-1:
        break
    if index == 0:
        a = np.insert(a, 0, 1000)
    if index == 3:
        a = np.insert(a, index, 1000)
print(a)

(0,)
(1,)
(2,)
(3,)
(4,)
[5 6 7 8 9]


In [96]:
a

array([5, 6, 7, 8, 9])

In [97]:
list(i for i in range(5, 10) if i != 7)

[5, 6, 8, 9]

In [98]:
a

array([5, 6, 7, 8, 9])

In [99]:
var_size_array = np.array([np.array([1, 2, 3]), np.array([4, 5]), np.array([6])])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [100]:
chrom[1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [101]:
alist = [np.arange(i) for i in range(3,7)]

In [102]:
alist

[array([0, 1, 2]),
 array([0, 1, 2, 3]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4, 5])]

In [103]:
for index, array in enumerate(alist):
    print(index)
    print(array)

0
[0 1 2]
1
[0 1 2 3]
2
[0 1 2 3 4]
3
[0 1 2 3 4 5]


In [104]:
a = np.array([1, 2, 4, 5, 0, 4, 0, 2, 4])
decode_a = a[a > 0]
decode_a

array([1, 2, 4, 5, 4, 2, 4])

In [105]:
a = []

In [106]:
a.append([x for x in range(18)])

In [107]:
a = [1, 2, 3]
b = [2, 3, 4]
c = []

In [108]:
a + b + c

[1, 2, 3, 2, 3, 4]

In [109]:
a = []
b = list(np.array([1, 2, 3]))

In [110]:
a += b

In [111]:
a

[1, 2, 3]

In [112]:
a = [1, 2, 0, 1, 2]
b = np.where(np.array(a)== 0)[0]

In [113]:
b

array([2])

In [114]:
index = np.argsort(a)[::-1]

In [115]:
index

array([4, 1, 3, 0, 2])

In [116]:
a[[1:3 ]]=[3,4]

SyntaxError: invalid syntax (2381113786.py, line 1)

In [117]:
a = [1, 2, 3, 0]
a[a == 0]

1

In [118]:
df = pd.read_excel('./time_matrix.xlsx')

In [119]:
df

到达门店简称      配送中心      安庆宜秀      蚌埠禹会      常州武进      常州新北      滁州琅琊  \
0    配送中心       NaN  6.337596  5.875281  0.953701  0.933475  4.034315   
1    安庆宜秀  6.337596       NaN  2.125058  5.442518  5.518224  2.771824   
2    蚌埠禹会  5.875281  2.125058       NaN  4.921730  4.949964  1.849046   
3    常州武进  0.953701  5.442518  4.921730       NaN  0.131327  3.080845   
4    常州新北  0.933475  5.518224  4.949964  0.131327       NaN  3.115715   
5    滁州琅琊  4.034315  2.771824  1.849046  3.080845  3.115715       NaN   
6    杭州拱墅  1.242959  5.711959  5.668258  1.333788  1.437562  3.844248   
7    杭州江干  1.249636  5.830667  5.798626  1.426355  1.524564  3.974835   
8    杭州萧山  1.280495  5.943329  5.926247  1.530151  1.623680  4.103372   
9    杭州余杭  1.053045  6.002440  5.904259  1.364355  1.448099  4.069067   
10   合肥肥东  5.526072  1.394592  0.920660  4.582610  4.633434  1.586111   
11   合肥蜀山  5.913256  1.195220  0.935763  4.971087  5.022838  1.973055   
12   湖州吴兴  0.848793  5.687185  5.459959  0.852636  0.946988  3.614894   
13   淮安经开  3.269184  4.519989  3.145582  2.430231  2.387256  1.760708   
14   淮南经开  6.422614  1.802731  0.654264  5.469908  5.506712  2.391144   
15   黄山屯溪  4.242423  2.455818  3.328060  3.479855  3.587158  2.272055   
16   嘉兴秀洲  0.848433  6.763431  6.516415  1.668515  1.692007  4.667568   
17   金华婺城  2.759926  4.814400  5.326495  2.493221  2.623658  3.705861   
18   丽水莲都  3.015833  5.589194  6.192520  3.009784  3.132321  4.572203   
19  连云港海州  3.730241  5.221707  3.593988  3.021284  2.948043  2.538589   
20   南京江宁  3.007367  3.526857  2.885134  2.056068  2.099728  1.036089   
21   宁波慈溪  1.977682  7.799126  7.671717  2.847231  2.866575  5.825235   
22   宁波鄞州  2.598018  8.337687  8.273574  3.469114  3.489369  6.429715   
23   上海宝山  1.932856  8.245797  7.789715  2.880033  2.841604  5.957170   
24   上海嘉定  1.521095  7.830530  7.386591  2.471183  2.436710  5.550755   
25   上海闵行  1.770938  8.025255  7.646195  2.724486  2.700341  5.804197   
26   上海浦东  2.051196  8.334023  7.922132  3.003750  2.972239  6.084416   
27   上海青浦  1.298356  7.551650  7.172012  2.250651  2.230644  5.328627   
28   绍兴越城  1.446827  6.540995  6.539685  1.990060  2.059269  4.712460   
29   苏州相城  0.382987  6.681070  6.255248  1.333781  1.316452  4.412539   
30   苏州园区  0.372537  6.632166  6.228330  1.309794  1.299955  4.383671   
31   宿迁宿城  4.568461  3.732390  1.945444  3.666600  3.649530  1.447160   
32   台州椒江  3.267530  8.287587  8.508487  3.991243  4.044720  6.705066   
33   泰州海陵  1.343085  5.578799  4.772107  0.731883  0.618588  2.996419   
34   温州龙湾  3.464356  7.361465  7.868857  3.913127  4.003498  6.158609   
35   无锡惠山  0.322126  6.089152  5.571722  0.660111  0.622112  3.735475   
36   无锡宜兴  1.166089  5.171514  4.791079  0.399607  0.529541  2.942052   
37   芜湖弋江  3.848963  2.527127  2.354079  2.930332  2.999509  0.874065   
38   徐州铜山  6.506320  3.121307  1.114473  5.567781  5.573254  2.645554   
39   盐城亭湖  1.829167  6.290819  5.227635  1.610908  1.481676  3.584398   
40   扬州邗江  2.105259  4.629798  3.821478  1.183885  1.174466  2.026497   
41   义乌稠江  2.165855  5.684559  5.986848  2.233393  2.348869  4.247624   
42   镇江新区  1.954018  4.674900  3.943725  1.018482  1.020550  2.127920   
43   舟山定海  3.390225  9.361149  9.205243  4.320141  4.318821  7.356295   

        杭州拱墅      杭州江干      杭州萧山  ...      温州龙湾      无锡惠山      无锡宜兴      芜湖弋江  \
0   1.242959  1.249636  1.280495  ...  3.464356  0.322126  1.166089  3.848963   
1   5.711959  5.830667  5.943329  ...  7.361465  6.089152  5.171514  2.527127   
2   5.668258  5.798626  5.926247  ...  7.868857  5.571722  4.791079  2.354079   
3   1.333788  1.426355  1.530151  ...  3.913127  0.660111  0.399607  2.930332   
4   1.437562  1.524564  1.623680  ...  4.003498  0.622112  0.529541  2.999509   
5   3.844248  3.974835  4.103372  ...  6.158609  3.735475  2.942052  0.874065   
6        NaN  0.130589  0.259297  ...  2.597605  1.302349  1.113992  3.400001   
7   0.130589       NaN  0.128962  ...  2.491941  1.340424  1.227700  

In [120]:
time_matrix = pd.read_excel('./time_matrix.xlsx')
time_matrix.set_index(['到达门店简称'], inplace=True)
time_matrix = time_matrix.to_numpy(dtype=float)

In [121]:
time_matrix
a = time_matrix

In [122]:
a[0, 2] + a[2, 14]+a[14, 38]

7.8682950025742855

In [123]:
a[0, 21] + a[21, 22] + a[22, 32] + a[32, 34] + a[34, 18] + a[18, 17]

7.715245899345241

In [124]:
a[0, 42] + a[42, 20] + a[20, 5] + a[5, 31] + a[31, 13] + a[13, 19]

7.881540826140201

In [125]:
a[0, 4] + a[4, 3] + a[3, 6] + a[6, 40] + a[40, 15]

7.8342609196519435

In [126]:
a[0, 8] + a[8, 29] + a[29, 35] + a[35, 9] + a[9, 7] + a[7, 36] + a[36, 41]

7.8739393462060905

In [127]:
a[23, 25] + a[25, 27] + a[27, 30] + a[30, 39]

3.8925192132790927

In [128]:
a[33, 37] + a[37, 10] + a[10, 11] + a[11, 1]

6.3865822959932785

In [129]:
a[0, 26] + a[26, 24] + a[24, 16] + a[16, 28] + a[28,43]

7.369457942251065

In [130]:
df = pd.read_excel('./数据.xlsx', sheet_name=0)
df.drop(columns=['配送中心', '允许到店时间段'], inplace=True)
df['时间属性'] = df['时间属性'].map({'夜配': 0, '日配': 1})
df2 = pd.DataFrame(['配送中心', '120.44739', '31.50353', 2]).T
df2.columns = df.columns
df = pd.concat([df2, df], ignore_index=True)
df.drop(index=[3, 7, 23], inplace=True)
df.reset_index(inplace=True)
print(df)

    index 到达门店简称          经度         纬度 时间属性
0       0   配送中心   120.44739   31.50353    2
1       1   安庆宜秀   117.06127   30.50783    0
2       2   蚌埠禹会   117.35315   32.93336    1
3       4   常州武进   119.94244   31.70086    0
4       5   常州新北   119.97131   31.83046    0
5       6   滁州琅琊   118.30538   32.29521    1
6       8   杭州拱墅   120.14209   30.31968    0
7       9   杭州江干   120.20517    30.2572    0
8      10   杭州萧山   120.26452   30.18505    0
9      11   杭州余杭   120.29986   30.41829    0
10     12   合肥肥东   117.47128   31.88525    1
11     13   合肥蜀山   117.26104   31.85117    1
12     14   湖州吴兴   120.12548   30.85752    1
13     15   淮安经开  119.021265  33.597506    1
14     16   淮南经开  117.025449  32.645947    1
15     17   黄山屯溪   118.33368   29.71138    1
16     18   嘉兴秀洲   120.70867   30.76454    1
17     19   金华婺城   119.57135   29.09521    1
18     20   丽水莲都    119.9127   28.44583    1
19     21  连云港海州   119.13128   34.56986    1
20     22   南京江宁    118.8399   31.95263    0
21     24 

In [131]:
send_array = df['时间属性']
send_array = send_array.to_numpy(dtype=int)
print(send_array)

[2 0 1 0 0 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 0 1]


In [132]:
send_array[2]

1

In [133]:
send_array[14]

1

In [134]:
send_array[38]

1

In [135]:
send_array[21]

1

In [136]:
send_array[22]

1

In [137]:
send_array[32]

1

In [138]:
send_array[34]

1

In [139]:
send_array[18]

1

In [140]:
send_array[17]

1

In [141]:
send_array[42]

0

In [142]:
send_array[20]

0

In [143]:
send_array[5]

1

In [144]:
send_array[31]

1

In [145]:
send_array[4]

0

In [146]:
send_array[3]

0

In [147]:
send_array[6]

0

In [148]:
send_array[40]

1

In [149]:
send_array[8]

0

In [150]:
send_array[29]

1

In [151]:
send_array[12]

1

In [152]:
send_array[23]

0

In [153]:
send_array[25]

0

In [154]:
send_array[33]

1

In [155]:
send_array[37]

1

In [156]:
send_array[10]

1

In [157]:
send_array[11]

1

In [158]:
send_array[1]

0

In [159]:
send_array[26]

0

In [160]:
df = pd.read_excel('./time_send.xlsx')

In [161]:
df

日期  门店名称  冷冻发货量(吨)  冷藏发货量(吨)  配送时间
0    1  宁波慈溪     0.188     0.565     1
1    1  无锡惠山     0.134     1.092     1
2    1  杭州余杭     0.956     0.635     0
3    1  上海闵行     0.740     0.210     0
4    1  泰州海陵     0.325     0.281     1
..  ..   ...       ...       ...   ...
93   4  杭州余杭     0.440     0.655     0
94   4  杭州江干     0.406     0.890     0
95   4  嘉兴秀洲     0.364     0.430     1
96   4  湖州吴兴     0.043     0.909     1
97   4  淮安经开     0.380     1.085     1

[98 rows x 5 columns]

In [162]:
a = df.groupby(['日期'])

In [163]:
b = list((a.get_group((4, ))['配送时间']).to_numpy())

In [164]:
b

[1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1]

In [165]:
b[0]

1

In [166]:
df = pd.read_excel('./数据.xlsx', sheet_name=0)
df.drop(columns=['配送中心', '允许到店时间段'], inplace=True)
df['时间属性'] = df['时间属性'].map({'夜配': 0, '日配': 1})
df2 = pd.DataFrame(['配送中心', '120.44739', '31.50353', 2]).T
df2.columns = df.columns
df = pd.concat([df2, df], ignore_index=True)
df.drop(index=[3, 7, 23], inplace=True)
df.reset_index(inplace=True)

In [167]:
send_data = pd.read_excel('./time_send.xlsx')
for i in send_data.index:
    filt = (df['到达门店简称'] == send_data.loc[i, '门店名称'])
    send_data.loc[i, '门店名称'] = df.loc[filt, '到达门店简称'].index[0]
send_data.index += 1

In [168]:
send_data

日期 门店名称  冷冻发货量(吨)  冷藏发货量(吨)  配送时间
1    1   21     0.188     0.565     1
2    1   35     0.134     1.092     1
3    1    9     0.956     0.635     0
4    1   25     0.740     0.210     0
5    1   33     0.325     0.281     1
..  ..  ...       ...       ...   ...
94   4    9     0.440     0.655     0
95   4    7     0.406     0.890     0
96   4   16     0.364     0.430     1
97   4   12     0.043     0.909     1
98   4   13     0.380     1.085     1

[98 rows x 5 columns]

In [169]:
time_matrix = pd.read_excel('./time_matrix.xlsx')
time_matrix.set_index(['到达门店简称'], inplace=True)
time_matrix = time_matrix.to_numpy(dtype=float)

df = pd.read_excel('./数据.xlsx', sheet_name=0)
df.drop(columns=['配送中心', '允许到店时间段'], inplace=True)
df['时间属性'] = df['时间属性'].map({'夜配': 0, '日配': 1})
df2 = pd.DataFrame(['配送中心', '120.44739', '31.50353', 2]).T
df2.columns = df.columns
df = pd.concat([df2, df], ignore_index=True)
df.drop(index=[3, 7, 23], inplace=True)
df.reset_index(inplace=True)

send_data = pd.read_excel('./time_send.xlsx')
for i in send_data.index:
    filt = (df['到达门店简称'] == send_data.loc[i, '门店名称'])
    send_data.loc[i, '门店名称'] = df.loc[filt, '到达门店简称'].index[0]
df3 = pd.DataFrame([0, 0, 0, 0, 0]).T
df3.columns = send_data.columns
send_data = pd.concat([df3, send_data], ignore_index=True)
send_data['总货量'] = send_data['冷冻发货量(吨)'] + send_data['冷藏发货量(吨)']

In [170]:
send_data

日期 门店名称  冷冻发货量(吨)  冷藏发货量(吨)  配送时间    总货量
0    0    0     0.000     0.000     0  0.000
1    1   21     0.188     0.565     1  0.753
2    1   35     0.134     1.092     1  1.226
3    1    9     0.956     0.635     0  1.591
4    1   25     0.740     0.210     0  0.950
..  ..  ...       ...       ...   ...    ...
94   4    9     0.440     0.655     0  1.095
95   4    7     0.406     0.890     0  1.296
96   4   16     0.364     0.430     1  0.794
97   4   12     0.043     0.909     1  0.952
98   4   13     0.380     1.085     1  1.465

[99 rows x 6 columns]

In [171]:
distance_matrix = pd.read_excel('./distance_matrix.xlsx')
distance_matrix.set_index(['到达门店简称'], inplace=True)
distance_matrix = distance_matrix.to_numpy(dtype=float)
distance_matrix

array([[         nan, 380.25575973, 352.51683155, ..., 129.95130303,
        117.24109713, 203.41349258],
       [380.25575973,          nan, 127.50349544, ..., 341.07351673,
        280.49400729, 561.66893525],
       [352.51683155, 127.50349544,          nan, ..., 359.21085434,
        236.62350371, 552.31460183],
       ...,
       [129.95130303, 341.07351673, 359.21085434, ...,          nan,
        174.28684905, 229.67715924],
       [117.24109713, 280.49400729, 236.62350371, ..., 174.28684905,
                 nan, 320.18210794],
       [203.41349258, 561.66893525, 552.31460183, ..., 229.67715924,
        320.18210794,          nan]])

In [172]:
a = np.array([1, 2, 3])
a[0]

1